version: "3"

services:
  web: &default
    build:
      context: .
    command: bin/start.sh
    ports:
      - 3001:3000
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - bundle:/bundle
    links:
      - db

  db:
    image: postgres:13.3
    environment:
      - PGDATA=/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/pgdata

  karafka:
    <<: *default
    ports: []
    command: bin/karafka server
    external_links:
      - kafka

volumes:
  bundle:
  pgdata:

networks:
  pilot_network:
    external: true
