default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &dev
  <<: *default
  database: manager_development
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV["DATABASE_USERNAME"] %>

test:
  <<: *dev
  database: manager_test
