version: "3"

services:
  web: &default
    build:
      context: .
    command: bin/start.sh
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - bundle:/bundle
    links:
      - db
    networks:
      - default
      - pilot_network

  db:
    image: postgres:13.3
    environment:
      - PGDATA=/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/pgdata

  karafka:
    <<: *default
    ports: []
    command: bin/karafka server
    links:
      - kafka
    external_links: []

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - default
      - pilot_network

volumes:
  bundle:
  pgdata:

networks:
  pilot_network:
    external: true
